### PR TITLE
Added a dark theme for the issue viewer

### LINKED ISSUE #121: Provide Dark Theme for Issue Viewer
Once I have settings, allow the user to select a light and a dark CSS theme for the issue viewer.

### PR DESCRIPTION
**Pull request by rprouse**
Fixes #121

### CODE REVIEW

**Comment by sharwell** [comment]
Can you paste a screenshot into this for reference? :+1:

**Comment by rprouse** [comment]
@sharwell, here you go. Like the look?

2015-04-25 14_10_53-start page - microsoft visual studio - experimental instance

**Comment by sharwell** [comment]
Nice job. :+1:

**Comment by dgunderson** [comment]
Has this been pushed to the latest install?  I'm not finding a way to enable it.

**Pull request merged**
